name: First Workflow

on:
  workflow_dispatch:

env:
    Cow_Says: "Moo!"

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
        MY_VAR: "Hello, world!"

    steps:
    - name: Step one
      run: echo $MY_VAR
    - name: Step two
      run: echo "Log from step two"
      
  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
    - name: Cowsays
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: $Cow_Says
        color: 'red'